//  AdobeQoeDataDetails.swift

/// Qoe data details information related to the experience event.
///
/// - SeeAlso: [Adobe XDM QoeDataDetails Schema](https://github.com/adobe/xdm/blob/master/docs/reference/datatypes/qoedatadetails.schema.md)
struct AdobeQoeDataDetails: Codable {
    /// The average bitrate (in kbps). The value is predefined buckets at 100kbps intervals.
    var bitrateAverage: String?

    /// The bitrate value (in kbps).
    var bitrate: Int?

    /// The average bitrate (in kbps, integer).
    var bitrateAverageBucket: Int?

    /// The number of streams in which bitrate changes occurred.
    var hasBitrateChangeImpactedStreams: Bool?

    /// The number of bitrate changes.
    var bitrateChangeCount: Int?

    /// The number of streams in which frames were dropped.
    var hasDroppedFrameImpactedStreams: Bool?

    /// The number of frames dropped during playback of the main content.
    var droppedFrames: Int?

    /// The number of times a user quit the video before its start.
    var isDroppedBeforeStart: Bool?

    /// The current value of the stream frame-rate (in frames per second).
    var framesPerSecond: Int?

    /// Describes the duration (in seconds) passed between video load and start.
    var timeToStart: Int?

    /// The number of streams impacted by buffering.
    var hasBufferImpactedStreams: Bool?

    /// The number of buffer events.
    var bufferCount: Int?

    /// The total amount of time, in seconds, spent buffering.
    var bufferTime: Int?

    /// The number of streams in which an error event occurred.
    var hasErrorImpactedStreams: Bool?

    /// The number of errors that occurred.
    var errorCount: Int?

    /// The number of streams in which a stalled event occurred.
    var hasStallImpactedStreams: Bool?

    /// The number of times the playback was stalled during a playback session.
    var stallCount: Int?

    /// The total time (seconds) the playback was stalled during a playback session.
    var stallTime: Int?

    /// The unique error IDs generated by the player SDK.
    var playerSdkErrors: [String]?

    /// The unique error IDs from any external source, e.g., CDN errors.
    var externalErrors: [String]?

    /// The unique error IDs generated by Media SDK during playback.
    var mediaSdkErrors: [String]?
}
