source "https://rubygems.org"

# Cocoapods 1.15 introduced a bug which breaks the build.
gem 'cocoapods', '>= 1.13', '< 1.15'
gem 'activesupport', '>= 6.1.7.5', '< 7.1.0'
gem 'concurrent-ruby', '1.3.4'
