package com.theoplayer.reactnative.adobe.edge.api

/**
 * Qoe data details information related to the experience event.
 *
 * @see <a href="https://github.com/adobe/xdm/blob/master/docs/reference/datatypes/qoedatadetails.schema.md">Adobe XDM QoeDataDetails Schema</a>
 */
data class AdobeQoeDataDetails(
  // The average bitrate (in kbps). The value is predefined buckets at 100kbps intervals.
  val bitrateAverage: String? = null,
  // The bitrate value (in kbps).
  val bitrate: Int? = null,
  // The average bitrate (in kbps, integer).
  val bitrateAverageBucket: Int? = null,
  // The number of streams in which bitrate changes occurred.
  val hasBitrateChangeImpactedStreams: Boolean? = null,
  // The number of bitrate changes.
  val bitrateChangeCount: Int? = null,
  // The number of streams in which frames were dropped.
  val hasDroppedFrameImpactedStreams: Boolean? = null,
  // The number of frames dropped during playback of the main content.
  val droppedFrames: Int? = null,
  // The number of times a user quit the video before its start.
  val isDroppedBeforeStart: Boolean? = null,
  // The current value of the stream frame-rate (in frames per second).
  val framesPerSecond: Int? = null,
  // Describes the duration (in seconds) passed between video load and start.
  val timeToStart: Int? = null,
  // The number of streams impacted by buffering.
  val hasBufferImpactedStreams: Boolean? = null,
  // The number of buffer events.
  val bufferCount: Int? = null,
  // The total amount of time, in seconds, spent buffering.
  val bufferTime: Int? = null,
  // The number of streams in which an error event occurred.
  val hasErrorImpactedStreams: Boolean? = null,
  // The number of errors that occurred.
  val errorCount: Int? = null,
  // The number of streams in which a stalled event occurred.
  val hasStallImpactedStreams: Boolean? = null,
  // The number of times the playback was stalled during a playback session.
  val stallCount: Int? = null,
  // The total time (seconds) the playback was stalled during a playback session.
  val stallTime: Int? = null,
  // The unique error IDs generated by the player SDK.
  val playerSdkErrors: List<String>? = null,
  // The unique error IDs from any external source, e.g., CDN errors.
  val externalErrors: List<String>? = null,
  // The unique error IDs generated by Media SDK during playback.
  val mediaSdkErrors: List<String>? = null
)
