export enum EventType {
  sessionStart = 'sessionStart',
  play = 'play',
  bitrateChange = 'bitrateChange',
  bufferStart = 'bufferStart',
  pauseStart = 'pauseStart',
  adBreakStart = 'adBreakStart',
  adStart = 'adStart',
  adComplete = 'adComplete',
  adSkip = 'adSkip',
  adBreakComplete = 'adBreakComplete',
  chapterStart = 'chapterStart',
  chapterSkip = 'chapterSkip',
  chapterComplete = 'chapterComplete',
  error = 'error',
  sessionEnd = 'sessionEnd',
  sessionComplete = 'sessionComplete',
  statesUpdate = 'statesUpdate',
  updatePlayhead = 'updatePlayhead',
  seekStart = 'seekStart',
  seekEnd = 'seekEnd',
}
