require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

target 'TheoplayerConvivaExample' do
  platform :ios, min_ios_version_supported
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
  pod 'THEOplayerSDK-basic', :path => './TheoSDK'
end

# target 'TheoplayerConvivaExample-tvOS' do
#   platform :tvos, min_tvos_version_supported
#   config = use_native_modules!
#   use_react_native!(:path => config[:reactNativePath])
#   pod 'THEOplayerSDK-basic', :path => './TheoSDK'
# end

post_install do |installer|
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
